try{
    console.log(x);
}
catch(error) {
    console.error(error);
}
finally{
    console.log("This Alaways Executes");
}
console.log("You Have Reached the End");